server:
  port: 8090

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: CUSTOMERSERVICE
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/auth/**,/customers/**
        - id: METERSERVICE
          uri: lb://METERSERVICE
          predicates:
            - Path=/meters/**,/usage/**
        - id: BILLINGSERVICE
          uri: lb://BILLINGSERVICE
          predicates:
            - Path=/billing/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka