server:
  port: 8090

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: CUSTOMERSERVICE
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/auth/**,/customers/**
          filters:
            - AuthenticationFilter
        - id: METERSERVICE
          uri: lb://METERSERVICE
          predicates:
            - Path=/meters/**,/usage/**
          filters:
            - AuthenticationFilter
        - id: BILLINGSERVICE
          uri: lb://BILLINGSERVICE
          predicates:
            - Path=/billing/**
          filters:
            - AuthenticationFilter
        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}